dist: xenial
language: generic
cache:
  directories:
  - "$HOME/.stack"
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar
  xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack --no-terminal --install-ghc test --only-dependencies
script:
- stack --no-terminal test --haddock --no-haddock-deps
before_deploy:
- zip -r $TRAVIS_COMMIT .
- mkdir -p upload
- mv $TRAVIS_COMMIT.zip upload/$TRAVIS_COMMIT.zip
deploy:
- provider: s3
  access_key_id: "$ACCESS_KEY_ID"
  secret_access_key:
    secure: ZmKcQ3fg5E4+a9S73HmCJzRJKMLIyjiq/QYFjpFFHk84fqmpvzSkoKmtSpjjq4DDoWRfzoKJW2sDuV56ADKCGVb7BZuMTUnecXuT+LZMJAN2eCfDwBKhKdzo7h36Fux6guAUrGN6y+RxG6YqqdLl/9JTY601NkYLOfvr0YS8twlK+JW15a4gYwgY/mekmHynJWGgJEoKjWnKFhR/yWkv4oLern4qHpryADKD7kZsBY9cbk/aqvcKe7RGt739VrvBAYE115GLAHlc+ZylIXVoJu29wmHilroUawfbSPckIuogkUp7i1H28Cfl+UvVPHIlmSE8PoysqDTHmITaH2amSwFgAbz06OnSGf1GlJEJImHRaSc4iIk1iqIKyEKfJP8pZNxRrKvD1pSQ0VjCRggPwZ4gtZqBUpyY+7QF2aRopRZIggOVwETENxJLDK7cvUpTW5dWWEPI9DpddmJfz3q2k50hOE/Jn+stXu31ZlDWlpnJDpZtY9LLBx89YhoVCShG64Y0ntEj5aFID9Vhdf3fjxqVu+TzaIEsh7qJF6htzd2siQ69frMkdjKFtJd91BBUGmZnNcizWRKkc0eHJURWgWVXnT4uw/j3PzksgDtk8ClLpTwC9FRywbACFrhQwALKV89SX9hEt+nOPU4v3V+NuVUDfEn6bIKGzoG+CgdGXs8=
  skip_cleanup: true
  local_dir: upload
  bucket: tslaq-deployments
  upload-dir: tslaq-event-tracker
  dot_match: true
  acl: private
  on:
    repo: amiri/tslaq-event-tracker
- provider: codedeploy
  access_key_id: "$ACCESS_KEY_ID"
  secret_access_key:
    secure: ZmKcQ3fg5E4+a9S73HmCJzRJKMLIyjiq/QYFjpFFHk84fqmpvzSkoKmtSpjjq4DDoWRfzoKJW2sDuV56ADKCGVb7BZuMTUnecXuT+LZMJAN2eCfDwBKhKdzo7h36Fux6guAUrGN6y+RxG6YqqdLl/9JTY601NkYLOfvr0YS8twlK+JW15a4gYwgY/mekmHynJWGgJEoKjWnKFhR/yWkv4oLern4qHpryADKD7kZsBY9cbk/aqvcKe7RGt739VrvBAYE115GLAHlc+ZylIXVoJu29wmHilroUawfbSPckIuogkUp7i1H28Cfl+UvVPHIlmSE8PoysqDTHmITaH2amSwFgAbz06OnSGf1GlJEJImHRaSc4iIk1iqIKyEKfJP8pZNxRrKvD1pSQ0VjCRggPwZ4gtZqBUpyY+7QF2aRopRZIggOVwETENxJLDK7cvUpTW5dWWEPI9DpddmJfz3q2k50hOE/Jn+stXu31ZlDWlpnJDpZtY9LLBx89YhoVCShG64Y0ntEj5aFID9Vhdf3fjxqVu+TzaIEsh7qJF6htzd2siQ69frMkdjKFtJd91BBUGmZnNcizWRKkc0eHJURWgWVXnT4uw/j3PzksgDtk8ClLpTwC9FRywbACFrhQwALKV89SX9hEt+nOPU4v3V+NuVUDfEn6bIKGzoG+CgdGXs8=
  bucket: tslaq-deployments
  bundle_type: zip
  key: tslaq-event-tracker/$TRAVIS_COMMIT.zip
  application: tslaq-event-tracker
  deployment_group: tslaq-event-tracker
  wait_until_deployed: true
