dist: bionic
language: generic
cache:
  directories:
  - "$HOME/.stack"
  - "$HOME/.yarn-cache"
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar
  xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
- echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt-get update && sudo apt-get install --no-install-recommends yarn
install:
- stack --no-terminal --install-ghc test --only-dependencies
script: ./scripts/travis-script.sh
before_deploy:
- zip -r $TRAVIS_COMMIT .
- mkdir -p upload
- mv $TRAVIS_COMMIT.zip upload/$TRAVIS_COMMIT.zip
deploy:
- provider: s3
  access_key_id: "$ACCESS_KEY_ID"
  secret_access_key:
    secure: byO/ukdKtC+ApP7in1BYyTJm3ba8a7hPgXLrXAw/0QSOStYZ5qRggOeuEAQzCz+XaL8MQ8PckIL+siGoU93BEN0EvbDooaMiZZ+EShINhzRIfRFKdB3f+vTtDyEtMtHy2nX5f37aJrWWbtFeGmhgfaluSbYVl6PBhANKSD9Fr8EVM/PFFHtUsX7yL3JYPjtdl7ke+NMR7gf8wrQkBMRsMxqCz+eLOElcfdLNqkADYLY7ih9lPc7O41832/4sfDCr2uuSKXpMRu/GXHulisxjqsVePRajfEJOEb8SPPu6lVgl61eZ7NMsBVC/JFQJxBxgGL0+8C3+uN4mJThDP1gZd7YKCLsih/fwpV5QKfU3mM0SkA7FdI3eGut8MDyxyzcqY8igbXkKsjZ/AMF6qDReSQxsKEc0thzcgm1KY/65c6suHH+qT86tKam/hyawiXDxTs4yamaiLK/D0uQ/MmzXpnsS/ryiSRpyuHyLdd13I887elVhUA57E+++2LRYys5J9SU9u4G03uFCelqxKEYx1VoaJ16niDEDk0k8+RcHj65kd8pPTHYf/4XYd7JmTUCvhAdGjrvKlPmmpaqJ8k6b8zDpk20l7ecJHjpaclSpcToTfadX9PKfQD2woCtmEXx4gvswtbp144exLdNaGiREWZnrvaiwvvYTaNtdoIw8e5E=
  skip_cleanup: true
  local_dir: upload
  bucket: tslaq-deployments
  upload-dir: tslaq-event-tracker
  dot_match: true
  acl: private
  on:
    repo: amiri/tslaq-event-tracker
- provider: codedeploy
  access_key_id: "$ACCESS_KEY_ID"
  secret_access_key:
    secure: byO/ukdKtC+ApP7in1BYyTJm3ba8a7hPgXLrXAw/0QSOStYZ5qRggOeuEAQzCz+XaL8MQ8PckIL+siGoU93BEN0EvbDooaMiZZ+EShINhzRIfRFKdB3f+vTtDyEtMtHy2nX5f37aJrWWbtFeGmhgfaluSbYVl6PBhANKSD9Fr8EVM/PFFHtUsX7yL3JYPjtdl7ke+NMR7gf8wrQkBMRsMxqCz+eLOElcfdLNqkADYLY7ih9lPc7O41832/4sfDCr2uuSKXpMRu/GXHulisxjqsVePRajfEJOEb8SPPu6lVgl61eZ7NMsBVC/JFQJxBxgGL0+8C3+uN4mJThDP1gZd7YKCLsih/fwpV5QKfU3mM0SkA7FdI3eGut8MDyxyzcqY8igbXkKsjZ/AMF6qDReSQxsKEc0thzcgm1KY/65c6suHH+qT86tKam/hyawiXDxTs4yamaiLK/D0uQ/MmzXpnsS/ryiSRpyuHyLdd13I887elVhUA57E+++2LRYys5J9SU9u4G03uFCelqxKEYx1VoaJ16niDEDk0k8+RcHj65kd8pPTHYf/4XYd7JmTUCvhAdGjrvKlPmmpaqJ8k6b8zDpk20l7ecJHjpaclSpcToTfadX9PKfQD2woCtmEXx4gvswtbp144exLdNaGiREWZnrvaiwvvYTaNtdoIw8e5E=
  bucket: tslaq-deployments
  bundle_type: zip
  key: tslaq-event-tracker/$TRAVIS_COMMIT.zip
  application: tslaq-event-tracker
  deployment_group: tslaq-event-tracker
  wait_until_deployed: true
