dist: xenial
language: generic
cache:
  directories:
  - "$HOME/.stack"
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar
  xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack --no-terminal --install-ghc test --only-dependencies
script:
- stack --no-terminal test --haddock --no-haddock-deps
before_deploy:
- zip -r $TRAVIS_COMMIT .
- mkdir -p upload
- mv $TRAVIS_COMMIT.zip upload/$TRAVIS_COMMIT.zip
deploy:
- provider: s3
  access_key_id: "$ACCESS_KEY_ID"
  secret_access_key:
    secure: PJcnXJiWHNxaVD/BA6xe69MMoYr8Y1EtPaPt4NaHqdhOZvoCOwGZHiiTKRa0MniYH+QfHfD166zj2c9sRm1eX8j+a/zGD/awmi7NW4GH7Byk97eP8iasNSmvHbqw4K6QXODbg4bB9VrGY5zHkWbTYXXc7EllEwm2K8uu1fkBOCzeeyHy81oapWD1qoAdrE4yoTu3FIdMvDte64YJlO9lbBH1Agavgv96SQZduV9y29VkHwi7NrTGeIqBFb/zIrX0F+pxRDVFKeGZgjqixgJtqk6Vljw+ZGxesZd9vxV6ppc6mFvOZv1wKKT4m3KCT96aB6sTaYF/uv0pYAKg680qGno5Sn9QNnCspOSg2zwN392Tvs+nSU8cEf5/e+P0Tso9ImjNwJgamK/hXBOAX+gUS2eZtwRcKMnrD3i1WrqSyL+6/VaCnB2iLqKVS/yPuwH2xpz19nbMPhDvpB7q3L+04jXEJErikpnLcP/dgR5/BrS6SL06w7UL4vIhK0tkDk2wvYk80IY5AyTDrRke3FLsPqhrgRFK/dq7ZTjdesaV7e3r0q1YHWZQOGuxYFknqae6Sr+uSi9GdsApfXAgh4/gPEt98zxah+Szjd43Igu5DrX8JUitaiInrTCxw/7g0knoURy7vTHU30NWm9OXSDe4YzgvmeAq5S86BNLe+sUzBIw=
  skip_cleanup: true
  local_dir: upload
  bucket: tslaq-deployments
  upload-dir: tslaq-event-tracker
  dot_match: true
  acl: private
  on:
    repo: amiri/tslaq-event-tracker
- provider: codedeploy
  access_key_id: "$ACCESS_KEY_ID"
  secret_access_key:
    secure: PJcnXJiWHNxaVD/BA6xe69MMoYr8Y1EtPaPt4NaHqdhOZvoCOwGZHiiTKRa0MniYH+QfHfD166zj2c9sRm1eX8j+a/zGD/awmi7NW4GH7Byk97eP8iasNSmvHbqw4K6QXODbg4bB9VrGY5zHkWbTYXXc7EllEwm2K8uu1fkBOCzeeyHy81oapWD1qoAdrE4yoTu3FIdMvDte64YJlO9lbBH1Agavgv96SQZduV9y29VkHwi7NrTGeIqBFb/zIrX0F+pxRDVFKeGZgjqixgJtqk6Vljw+ZGxesZd9vxV6ppc6mFvOZv1wKKT4m3KCT96aB6sTaYF/uv0pYAKg680qGno5Sn9QNnCspOSg2zwN392Tvs+nSU8cEf5/e+P0Tso9ImjNwJgamK/hXBOAX+gUS2eZtwRcKMnrD3i1WrqSyL+6/VaCnB2iLqKVS/yPuwH2xpz19nbMPhDvpB7q3L+04jXEJErikpnLcP/dgR5/BrS6SL06w7UL4vIhK0tkDk2wvYk80IY5AyTDrRke3FLsPqhrgRFK/dq7ZTjdesaV7e3r0q1YHWZQOGuxYFknqae6Sr+uSi9GdsApfXAgh4/gPEt98zxah+Szjd43Igu5DrX8JUitaiInrTCxw/7g0knoURy7vTHU30NWm9OXSDe4YzgvmeAq5S86BNLe+sUzBIw=
  bucket: tslaq-deployments
  bundle_type: zip
  key: tslaq-event-tracker/$TRAVIS_COMMIT.zip
  application: tslaq-event-tracker
  deployment_group: tslaq
  wait_until_deployed: true
