flags: {}
packages:
  - .
extra-deps:
  - amazonka-secretsmanager-1.6.1
  - aws-cloudfront-signer-1.1.0.3
  - aws-easy-0.1.0.2
  - command-0.1.1
  - monad-metrics-0.2.1.4
  - wai-middleware-metrics-0.2.4
  - servant-quickcheck-0.0.7.4
  - tasty-hedgehog-1.0.0.1
  - hedgehog-1.0
  - amazonka-1.6.1
  - amazonka-core-1.6.1
  - amazonka-dynamodb-1.6.1
  - amazonka-s3-1.6.1
  - http-client-0.5.14
  - clock-0.7.2
  - servant-errors-0.1.3.1
  - lens-regex-pcre-1.1.0.0
  - pcre-light-0.4.1.0
  - hailgun-0.4.2
resolver: lts-14.14
